version: '3.8'
services:
  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/init.prod.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
  
    adminer:
      image: adminer
      restart: always
      ports:
      - "8080:8080"

volumes:
  pg_data:
